name: Basic Workflow

on: [push]

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "ðŸ‘‹ Hello Vivek! GitHub Actions is working."

      - name: Show Current Directory
        run: pwd

      - name: List Files
        run: ls -la
